version: '3'
services:
  frontend:
    build: frontend/
    restart: on-failure
    volumes:
      # DB_PATH=/Users/phb514/custom_software/parse_textgrids/output docker-compose up -d --build
      # Win PowerShell: $env:DB_PATH='C:\custom_software\parse_textgrids\output' ; $env:CODE_PATH='C:\custom_software\lanchart_partitur' ; docker-compose up -d --build
      - $DB_PATH:/opt/output
      - $CODE_PATH:/opt/lanchart_partitur
    ports:
      # <host port>:<docker port>! 5000: Flask app default port
      - "5005:5000"
